<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fem</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>optistruct</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment1</key>
		<dict>
			<key>match</key>
			<string>(\$.*)</string>
			<key>name</key>
			<string>comment.line.character.fem</string>
		</dict>
		<key>comment2</key>
		<dict>
			<key>match</key>
			<string>(^(//|#).*)</string>
			<key>name</key>
			<string>comment.line.character.fem</string>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=.{80})(.*)</string>
			<key>name</key>
			<string>invalid.illegal.fem</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fem</string>
	<key>uuid</key>
	<string>DF0D287A-09ED-47D6-816C-5B53D5CCFA27</string>
</dict>
</plist>
