<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fem</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>OptiStruct Bulk Data Format</string>
	<key>patterns</key>
	<array></array>
	<key>repository</key>
	<dict></dict>
	<key>scopeName</key>
	<string>source.fem</string>
	<key>uuid</key>
	<string>DF0D287A-09ED-47D6-816C-5B53D5CCFA27</string>
</dict>
</plist>
