<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fem</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>optistruct</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#io.options.section</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#subcase.information.section</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment1</key>
		<dict>
			<key>match</key>
			<string>(\$.*)</string>
			<key>name</key>
			<string>comment.line.character.fem</string>
		</dict>
		<key>comment2</key>
		<dict>
			<key>match</key>
			<string>(^(//|#).*)</string>
			<key>name</key>
			<string>comment.line.character.fem</string>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=.{80})(.*)</string>
			<key>name</key>
			<string>invalid.illegal.fem</string>
		</dict>
		<key>io.options.section</key>
		<dict>
			<key>match</key>
			<string>^(@HYPERFORM|ACCELERATION|ASSIGN|AUTOSPC|CDSMETH|CFAILURE|CHECK|CMDE|CMKE|CMSE|CONTF|CSTRAIN|CSTRESS|DAMAGE|DEBUG|DENSITY|DESGLB|DESHIS|DGLOBAL|DISPLACEMENT|DMIGNAME|DRESPONSE|DSA|ECHO|ECHOON|ECHOOFF|EDE|EIGVNAME|EKE|ELFORCE|ELSTRESS|ENDLOAD|ENERGY|ERP|ESE|FLUX|FORCE|FOS|GPFORCE|GPKE|GPSTRAIN|GPSTRESS|GSTRESS|HISOUT|HYBDAMP|INCLUDE|LIFE|LOADLIB|MBFORCE|MECHCHECK|MODALDE|MODALKE|MODALSE|MODEL|MPCFORCE|MSGLMT|NLLOAD|NLRESTART|NOISEXYZ|OFREQUENCY|OLOAD|OMODES|OTIME|OUTFILE|OUTPUT|PFGRID|PFMODE|PFPANEL|PFPATH|POWERFLOW|PRESSURE|PRETBOLT|PROPERTY|RBODY|RCROSS|REQUEST|RESPRINT|RESTART|RESTARTR|RESTARTW|RIGID|RNFLOW|SACCELERATION|SCREEN|SDISPLACEMENT|SENSITIVITY|SENSOUT|SHAPE|SINTENS|SPCFORCE|SPL|SPOWER|STRAIN|STRESS|SUBTITLE|SVELOCITY|SYSSETTING|TCURVE|THERMAL|THICKNESS|THIN|TITLE|TMPDIR|TTERM|UNITS|VELOCITY|XTITLE|XYPEAK|XYPLOT|XYPUNCH|YTITLE)(?=([\s|\W]))</string>
			<key>name</key>
			<string>entity.name.function.fem</string>
		</dict>
		<key>subcase.information.section</key>
		<dict>
			<key>match</key>
			<string>^(A2GG|ANALYSIS|B2GG|CMETHOD|CMSMETH|CNTNLSUB|CNTSTB|DEFORM|DESOBJ|DESSUB|DESVAR|DLOAD|EIGVRETRIEVE|EIGVSAVE|ESLTIME|EXCLUDE|FATDEF|FATPARM|FATSEQ|FLLWER|FREQUENCY|FSI|GLOBSUB|GROUNDCHECK|IC|IDGLOBAL|INVEL|K2GG|K2PP|K42GG|LABEL|LOAD|LOCATE|M2GG|MBSIM|METHOD|MFLUID|MINMAXorMAXMIN|MLOAD|MODCHG|NLOUT|MODESELECT|MODEWEIGHT|MODTRAK|MOTION|MPC|NLADAPT|NLMON|NLOAD|NLPARM|NONLINEAR|NORM|NSGE|NSM|P2G|P2GSUB|PEAKOUT|POST|PRETENSION|RADSND|RANDOM|REPCASE|REPGLB|REPSUB|RESVEC|RGYRO|RSPEC|RWALL|SDAMPING|SEINTPNT|SOLVTYP|SPC|STATSUB|SUBCASE|SUBCOM|SUBMODEL|SUBSEQ|SUPORT1|TEMPERATURE|TSTEP|TSTEPNL|TSTRU|WEIGHT|XHIST|XSTEP)(?=([\s|\W]))</string>
			<key>name</key>
			<string>entity.name.tag.fem</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fem</string>
	<key>uuid</key>
	<string>DF0D287A-09ED-47D6-816C-5B53D5CCFA27</string>
</dict>
</plist>
